baseURL = 'https://evanburkeen.com/'
languageCode = 'en-us'
title = 'Evan Burkeen'
theme = 'PaperMod'

[params]
    env = "production"
    customCSS = ["css/extended.css"]
    
    # This is the "switch" that brings your name back
    homeInfoParams = { Title = "Evan Burkeen", Content = "Political Science @ Yale" }

    # Ensure this is true to show the email icon
    ShowSocialButtons = true

    [[params.socialIcons]]
        name = "email"
        url = "mailto:evan.burkeen@yale.edu"