baseURL = 'https://evanburkeen.com/'
languageCode = 'en-us'
title = 'Evan Burkeen'
theme = 'PaperMod'

[params]
    env = "production"
    title = "Evan Burkeen"
    customCSS = ["css/extended.css"]
    
    # Date format: DD MON YYYY (e.g., 24 DEC 2025)
    DateFormat = "02 Jan 2006"
    ShowSocialButtons = true

    [params.homeInfoParams]
        Title = "Evan Burkeen"
        Content = "Political Science @ Yale"

    [[params.socialIcons]]
        name = "email"
        url = "mailto:evan.burkeen@yale.edu"

# Remove the menu section entirely to keep the top of the page empty