baseURL = 'https://evanburkeen.com/'
languageCode = 'en-us'
title = 'Evan Burkeen'
theme = 'PaperMod'

[params]
    env = "production"
    # Points to your specific path
    customCSS = ["css/extended/main.css"]
    
    # Force the Month to be caps via the CSS below, but set the structure here
    DateFormat = "02 Jan 2006"

    # Minimalist Bio
    [params.homeInfoParams]
        Title = "Evan Burkeen"
        Content = "Political Science @ Yale"

    [[params.socialIcons]]
        name = "email"
        url = "mailto:evan.burkeen@yale.edu"