baseURL = 'https://evanburkeen.com/'
languageCode = 'en-us'
title = 'Evan Burkeen'
theme = 'PaperMod'

[params]
    env = "production"
    # Note: We are using the default PaperMod path for reliability
    customCSS = ["css/extended.css"]
    DateFormat = "02 Jan 2006"

[params.homeInfoParams]
    Title = "Evan Burkeen"
    Content = "Political Science @ Yale"

[[params.socialIcons]]
    name = "email"
    url = "mailto:evan.burkeen@yale.edu"