baseURL = 'https://evanburkeen.com/'
theme = 'PaperMod'

[params]
    customCSS = ["css/extended.css"]

    [params.homeInfoParams]
        Title = "Evan Burkeen"
        Content = "Political Science @ Yale"

    # Minimalist settings to keep it looking professional
    ShowReadingTime = false
    displayFullContent = false
    hideMeta = true