baseURL = 'https://evanburkeen.com/'
languageCode = 'en-us'
title = 'Evan Burkeen'
theme = 'PaperMod'

[params]
    env = "production"
    customCSS = ["css/extended.css"]
    
    # High-end date format
    DateFormat = "02 Jan 2006"

    [params.homeInfoParams]
        Title = "Evan Burkeen"
        Content = "Political Science @ Yale"

    [[params.socialIcons]]
        name = "email"
        url = "mailto:evan.burkeen@yale.edu"